internal:
  txtOwnerId: [[ .InternalTxtOwnerId ]]
  domainFilters: [ [[ .InternalDomain ]] ]
  serviceAccount:
    annotations:
      [[- range $k, $v := .ServiceAccountAnnotations ]]
      [[ $k ]]: [[ $v ]]
      [[- end ]]
