on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
    secrets:
      tf_api_token:
        required: true
      tf_vars:
        required: true

jobs:
  cd:
    name: 'cd'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tf_api_token }}

      - name: init
        run: terraform init

      - name: apply
        run: |
          echo -e '${{ secrets.tf_vars }}' > secrets_override.auto.tfvars
          terraform apply -auto-approve
