on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
    secrets:
      tf_api_token:
        required: true
      gh_owner:
        required: true
      gh_token:
        required: true
      gh_ssh_private_key:
        required: true
      aws_access_key_id:
        required: false
      aws_secret_access_key:
        required: false

env:
  GITHUB_OWNER: ${{ secrets.gh_owner }}
  GITHUB_TOKEN: ${{ secrets.gh_token }}
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

jobs:
  ci:
    name: 'ci'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup ssh key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.gh_ssh_private_key }}"

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tf_api_token }}

      - name: fmt check
        run: terraform fmt -recursive -check

      - name: linter
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/v0.28.1/install_linux.sh | bash
          TFLINT_LOG=info tflint . -c ../.tflint.hcl

      - name: security check
        uses: bridgecrewio/checkov-action@v12.1128.0
        with:
          directory: .
          framework: terraform

      - name: init
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: terraform init

      - name: validate
        run: terraform validate

      - name: plan
        run: terraform plan
