on:
  workflow_call:

jobs:
  cd:
    name: 'cd'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: release
        run: npx semantic-release
