on:
  workflow_call:
    inputs:
      workdirs:
        required: true
        type: string
    secrets:
      gh_ssh_private_key:
        required: true

jobs:
  ci:
    name: 'ci'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup ssh key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.gh_ssh_private_key }}"

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: fmt check
        run: terraform fmt -recursive -check

      - name: linter
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/v0.28.1/install_linux.sh | bash
          CONFIG=$(if [ "$dir" = "." ];then echo -n '../.tflint.hcl';else echo -n '.tflint.hcl';fi)
          for dir in ${{ inputs.workdirs }}; do cd $dir; TFLINT_LOG=info tflint -c ${CONFIG} .; cd ..; done

      - name: security check
        run: |
          python3 -m pip install -U checkov==2.0.136
          for dir in ${{ inputs.workdirs }}; do cd $dir; checkov -d .; cd ..; done

      - name: validate
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          for dir in ${{ inputs.workdirs }}; do cd $dir; terraform init; cd ..; done
          for dir in ${{ inputs.workdirs }}; do cd $dir; terraform validate; cd ..; done
