apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
spec:
  project: default
  source:
    repoURL: git@[[ .GitProvider ]]:[[ .GitProject ]]/[[ .GitRepo ]].git
    targetRevision: [[ .GitDefaultBranch ]]
    path: external-dns
    helm:
      valueFiles:
        - values-[[ .Environment ]].yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
