apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: default
spec:
  project: default
  source:
    repoURL: git@[[ .GitProvider ]]:[[ .GitProject ]]/[[ .GitRepo ]].git
    targetRevision: [[ .GitDefaultBranch ]]
    path: ingress-nginx
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
