name: 'ci'

on:
  push:
    branches-ignore:
      - [[ .DefaultBranch ]]

jobs:
  [[- $root := . ]]
  [[- range $module := .Modules ]]
  [[ $module.Name ]]:
    name: 'terraform'
    uses: [[ $root.Project ]]/[[ $root.Repo ]]/.github/workflows/tf_infra_ci.yml@[[ $root.DefaultBranch ]]
    with:
      workdir: [[ $module.Name ]]
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
      gh_owner: ${{ secrets.GH_OWNER }}
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_ssh_private_key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  [[- end ]]
