name: '[[ .Module ]]_cd'

on:
  push:
    branches:
      - [[ .DefaultBranch ]]
    paths:
      - '[[ .Module ]]/**'
      - '.github/workflows/**'

jobs:
  terraform:
    uses: [[ .Project ]]/[[ .Repo ]]/.github/workflows/tf_infra_cd.yml@[[ .DefaultBranch ]]
    with:
      workdir: [[ .Module ]]
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
      tf_vars: |
        repo_password = "${{ secrets.TF_VAR_REPO_PASSWORD }}"
