name: 'cd'

on:
  push:
    branches:
      - [[ .DefaultBranch ]]

jobs:
  [[- $root := . ]]
  [[- range $module := .Modules ]]
  [[ $module.Name ]]:
    name: 'terraform'
    [[- with $module.Dependencies ]]
    needs: [ [[ StringsJoin . "," ]] ]
    [[- end ]]
    uses: [[ $root.Project ]]/[[ $root.Repo ]]/.github/workflows/tf_infra_cd.yml@[[ $root.DefaultBranch ]]
    with:
      workdir: [[ $module.Name ]]
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
      gh_owner: ${{ secrets.GH_OWNER }}
      gh_token: ${{ secrets.GH_TOKEN }}
  [[- end ]]
