name: 'ci'

on:
  push:
    branches-ignore:
      - [[ .DefaultBranch ]]

jobs:
  terraform:
    uses: [[ .Project ]]/[[ .Repo ]]/.github/workflows/tf_module_ci.yml@[[ .DefaultBranch ]]
    with:
      workdirs: [[ with .Modules ]]'[[ StringsJoin . " " ]]'[[ else ]]'.'[[ end ]]
